# File
DEFAULT_NAME = "README.md"
FILE_TYPES = (("Markdown File", "*.md"),)

# Interface
BG_COLOR = "gray15"
INTERFACE_COLOR = "gray25"
OUTLINE_COLOR = "gray35"

TEXT_COLOR = "white"

OUTLINE_WIDTH = 2
BUTTONS_PADDING = 10
TEXT_PADDING = 20

TITLE = "Programming office"

EDIT_DIALOG_HEIGHT = 350
EDIT_DIALOG_WIDTH = 500

# Font
FONT = "DejaVu Serif"
CODE_FONT = "JetBrains Mono"
SHEET_FONT_SIZE = 15
BUTTONS_FONT_SIZE = 15