# File
FILE_NAME = "README.md"
FILE_TYPES = (("Markdown File", "*.md"),)

# Interface
BG_COLOR = "gray15"
INTERFACE_COLOR = "gray25"
OUTLINE_COLOR = "gray35"

TEXT_COLOR = "white"

OUTLINE_WIDTH = 2
BUTTONS_PADDING = 10
TEXT_PADDING = 20

# Font
FONT = "Monospace"
SHEET_FONT_SIZE = 15
BUTTONS_FONT_SIZE = 15